### ISSUE TITLE
Not compatible with RSpec 3

### ISSUE THREAD

**Issue by andyw8** [endeepak/rspec-multi-mock#2]
I realise this project has not been updated for a long time, but just for the benefit of others, the gem is not compatible with RSpec 3. It fails with:

```
`require': cannot load such file -- rspec/core/mocking/with_rspec (LoadError)`
```

**Comment by endeepak** [comment]
Thanks for reporting this @andyw8. I would gladly accept a PR if it helps others

**Comment by endeepak** [comment]
Please try new version https://rubygems.org/gems/rspec-multi-mock/versions/0.3.0. Thanks to PR https://github.com/endeepak/rspec-multi-mock/pull/3 from @ebmeierj
