### ISSUE TITLE
Incompatible with newer versions of Mocha

### ISSUE THREAD

**Issue by Anbranin** [endeepak/rspec-multi-mock#4]
[This line here](https://github.com/endeepak/rspec-multi-mock/blob/b457f45ceaa27ac031f83c80eb82b196362d169e/lib/adapters/mocha.rb#L2) requires mocha/object, a file which was removed in mocha v0.13.0. I'm converting an older rails project to use rspec mocks from mocha and would love to be able to use this gem.

**Comment by endeepak** [comment]
@Anbranin Thanks for reporting the issue. I would need some time to look into this. If you have found a way to get it working with new version of mocha, please raise a pull request

**Comment by endeepak** [comment]
@Anbranin Thanks for the PR #5. Fix is released in new version https://rubygems.org/gems/rspec-multi-mock/versions/0.3.1
